#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/huawei/angler

PRODUCT_COPY_FILES += \
    vendor/huawei/angler/proprietary/system/etc/permissions/cneapiclient.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/cneapiclient.xml \
    vendor/huawei/angler/proprietary/system/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qcrilhook.xml \
    vendor/huawei/angler/proprietary/vendor/etc/acdbdata/angler/Angler_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/angler/Angler_Bluetooth_cal.acdb \
    vendor/huawei/angler/proprietary/vendor/etc/acdbdata/angler/Angler_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/angler/Angler_General_cal.acdb \
    vendor/huawei/angler/proprietary/vendor/etc/acdbdata/angler/Angler_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/angler/Angler_Global_cal.acdb \
    vendor/huawei/angler/proprietary/vendor/etc/acdbdata/angler/Angler_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/angler/Angler_Handset_cal.acdb \
    vendor/huawei/angler/proprietary/vendor/etc/acdbdata/angler/Angler_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/angler/Angler_Hdmi_cal.acdb \
    vendor/huawei/angler/proprietary/vendor/etc/acdbdata/angler/Angler_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/angler/Angler_Headset_cal.acdb \
    vendor/huawei/angler/proprietary/vendor/etc/acdbdata/angler/Angler_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/angler/Angler_Speaker_cal.acdb \
    vendor/huawei/angler/proprietary/vendor/etc/cne/profile.txt:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profile.txt \
    vendor/huawei/angler/proprietary/vendor/etc/diag/Angler_Radio-general.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/diag/Angler_Radio-general.cfg \
    vendor/huawei/angler/proprietary/vendor/etc/flp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/flp.conf \
    vendor/huawei/angler/proprietary/vendor/etc/lowi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lowi.conf \
    vendor/huawei/angler/proprietary/vendor/etc/perf-profile0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile0.conf \
    vendor/huawei/angler/proprietary/vendor/etc/pp_calib_data_SAMSUNG_S6E3HA3X01_5P7_1440P_CMD_DUAL0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pp_calib_data_SAMSUNG_S6E3HA3X01_5P7_1440P_CMD_DUAL0.xml \
    vendor/huawei/angler/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/huawei/angler/proprietary/vendor/firmware/BCM4358A3_RFSW.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM4358A3_RFSW.hcd \
    vendor/huawei/angler/proprietary/vendor/firmware/a420_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pfp.fw \
    vendor/huawei/angler/proprietary/vendor/firmware/a420_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pm4.fw \
    vendor/huawei/angler/proprietary/vendor/firmware/activity.napp:$(TARGET_COPY_OUT_VENDOR)/firmware/activity.napp \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b00 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b01 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b02 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b03 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b04 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b05 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b06 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b07 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b08 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b09 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b10 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b11 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b12 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b13 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b14 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b15 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b16 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b17 \
    vendor/huawei/angler/proprietary/vendor/firmware/adsp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.mdt \
    vendor/huawei/angler/proprietary/vendor/firmware/cpe.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b02 \
    vendor/huawei/angler/proprietary/vendor/firmware/cpe.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b04 \
    vendor/huawei/angler/proprietary/vendor/firmware/cpe.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b05 \
    vendor/huawei/angler/proprietary/vendor/firmware/cpe.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b06 \
    vendor/huawei/angler/proprietary/vendor/firmware/cpe.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b08 \
    vendor/huawei/angler/proprietary/vendor/firmware/cpe.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b10 \
    vendor/huawei/angler/proprietary/vendor/firmware/cpe.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b11 \
    vendor/huawei/angler/proprietary/vendor/firmware/cpe.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b12 \
    vendor/huawei/angler/proprietary/vendor/firmware/cpe.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b14 \
    vendor/huawei/angler/proprietary/vendor/firmware/cpe.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b16 \
    vendor/huawei/angler/proprietary/vendor/firmware/cpe.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b18 \
    vendor/huawei/angler/proprietary/vendor/firmware/cpe.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b20 \
    vendor/huawei/angler/proprietary/vendor/firmware/cpe.b21:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b21 \
    vendor/huawei/angler/proprietary/vendor/firmware/cpe.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.mdt \
    vendor/huawei/angler/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/huawei/angler/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/huawei/angler/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/huawei/angler/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/huawei/angler/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/huawei/angler/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/huawei/angler/proprietary/vendor/firmware/double_twist.napp:$(TARGET_COPY_OUT_VENDOR)/firmware/double_twist.napp \
    vendor/huawei/angler/proprietary/vendor/firmware/fingerpr.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b00 \
    vendor/huawei/angler/proprietary/vendor/firmware/fingerpr.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b01 \
    vendor/huawei/angler/proprietary/vendor/firmware/fingerpr.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b02 \
    vendor/huawei/angler/proprietary/vendor/firmware/fingerpr.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b03 \
    vendor/huawei/angler/proprietary/vendor/firmware/fingerpr.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.mdt \
    vendor/huawei/angler/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/huawei/angler/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/huawei/angler/proprietary/vendor/firmware/libpn548ad_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn548ad_fw.so \
    vendor/huawei/angler/proprietary/vendor/firmware/nanohub.full.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nanohub.full.bin \
    vendor/huawei/angler/proprietary/vendor/firmware/napp_list.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/napp_list.cfg \
    vendor/huawei/angler/proprietary/vendor/firmware/pickup_gesture.napp:$(TARGET_COPY_OUT_VENDOR)/firmware/pickup_gesture.napp \
    vendor/huawei/angler/proprietary/vendor/firmware/sig_motion.napp:$(TARGET_COPY_OUT_VENDOR)/firmware/sig_motion.napp \
    vendor/huawei/angler/proprietary/vendor/firmware/venus.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b00 \
    vendor/huawei/angler/proprietary/vendor/firmware/venus.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b01 \
    vendor/huawei/angler/proprietary/vendor/firmware/venus.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b02 \
    vendor/huawei/angler/proprietary/vendor/firmware/venus.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b03 \
    vendor/huawei/angler/proprietary/vendor/firmware/venus.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b04 \
    vendor/huawei/angler/proprietary/vendor/firmware/venus.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mdt \
    vendor/huawei/angler/proprietary/vendor/firmware/widevine.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b00 \
    vendor/huawei/angler/proprietary/vendor/firmware/widevine.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b01 \
    vendor/huawei/angler/proprietary/vendor/firmware/widevine.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b02 \
    vendor/huawei/angler/proprietary/vendor/firmware/widevine.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b03 \
    vendor/huawei/angler/proprietary/vendor/firmware/widevine.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.mdt \
    vendor/huawei/angler/proprietary/vendor/lib64/libmmcamera2_q3a_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera2_q3a_core.so \
    vendor/huawei/angler/proprietary/vendor/media/LMspeed_508.emd:$(TARGET_COPY_OUT_VENDOR)/media/LMspeed_508.emd \
    vendor/huawei/angler/proprietary/vendor/media/PFFprec_600.emd:$(TARGET_COPY_OUT_VENDOR)/media/PFFprec_600.emd \
    vendor/huawei/angler/proprietary/vendor/qcril.db:$(TARGET_COPY_OUT_VENDOR)/qcril.db \
    vendor/huawei/angler/proprietary/vendor/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/qcril_database/upgrade/1_version_intro.sql \
    vendor/huawei/angler/proprietary/vendor/qcril_database/upgrade/2_db_upgrade.sql:$(TARGET_COPY_OUT_VENDOR)/qcril_database/upgrade/2_db_upgrade.sql \
    vendor/huawei/angler/proprietary/vendor/qcril_database/upgrade/3_remove_ecc_999_from_us_and_canada.sql:$(TARGET_COPY_OUT_VENDOR)/qcril_database/upgrade/3_remove_ecc_999_from_us_and_canada.sql \
    vendor/huawei/angler/proprietary/vendor/xbin/wlutil:$(TARGET_COPY_OUT_VENDOR)/xbin/wlutil

PRODUCT_PACKAGES += \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libq3dtools_adreno \
    libq3dtools_esx \
    gatekeeper.msm8994 \
    keystore.msm8994 \
    nfc_nci.angler \
    sound_trigger.primary.msm8994 \
    tof.vl6180 \
    vulkan.msm8994 \
    lib-dplmedia \
    lib-ims-rcscmjni \
    lib-imsSDP \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs \
    lib-imsrcscm \
    lib-imsrcscmclient \
    lib-imsrcscmservice \
    lib-imss \
    lib-imsvt \
    lib-imsxml \
    lib-rcsimssjni \
    lib-rcsjni \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpdaemoninterface \
    lib-rtpsl \
    libC2D2 \
    libCB \
    libQSEEComAPI \
    libRSDriver_adreno \
    libacdb-fts \
    libacdbloader \
    libacdbmapper \
    libacdbrtac \
    libadiertac \
    libadreno_utils \
    libadsprpc \
    libaudioalsa \
    libbccQTI \
    libc2d30-a3xx \
    libc2d30-a4xx \
    libcne \
    libcneapiclient \
    libconfigdb \
    libdiag \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libdsutils \
    libgsl \
    libidl \
    libimscamera_jni \
    libimsmedia_jni \
    libkmcrypto \
    liblistensoundmodel2 \
    libllvm-glnext \
    libllvm-qcom \
    libllvm-qgl \
    libloc_api_v02 \
    libloc_ds_api \
    libmdmdetect \
    libmdsprpc \
    libmm-abl-oem \
    libmm-abl \
    libmm-als \
    libmm-disp-apis \
    libmm-qdcm \
    libmmcamera2_stats_algorithm \
    libnetmgr \
    libperipheral_client \
    libqcci_legacy \
    libqdi \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libqti-perfd-client \
    libril-qcril-hook-oem \
    librpmb \
    librs_adreno \
    librs_adreno_sha1 \
    libscale \
    libsmemlog \
    libssd \
    libsystem_health_mon \
    libthermalclient \
    libtime_genoff \
    libtzdrmgenprov \
    libvoice-svc \
    libwms \
    libxml \
    libwvdrmengine \
    libactuator_lc898212xd \
    libactuator_lc898212xd_camcorder \
    libactuator_lc898212xd_camera \
    libadm \
    libadpcmdec \
    libchromatix_imx179_liteon_common \
    libchromatix_imx179_liteon_cpp_liveshot \
    libchromatix_imx179_liteon_cpp_preview \
    libchromatix_imx179_liteon_cpp_snapshot \
    libchromatix_imx179_liteon_cpp_video \
    libchromatix_imx179_liteon_default_video \
    libchromatix_imx179_liteon_liveshot \
    libchromatix_imx179_liteon_postproc \
    libchromatix_imx179_liteon_preview \
    libchromatix_imx179_liteon_snapshot \
    libchromatix_imx179_liteon_video_binning \
    libchromatix_imx179_sunny_common \
    libchromatix_imx179_sunny_cpp_liveshot \
    libchromatix_imx179_sunny_cpp_preview \
    libchromatix_imx179_sunny_cpp_snapshot \
    libchromatix_imx179_sunny_cpp_video \
    libchromatix_imx179_sunny_default_video \
    libchromatix_imx179_sunny_liveshot \
    libchromatix_imx179_sunny_postproc \
    libchromatix_imx179_sunny_preview \
    libchromatix_imx179_sunny_snapshot \
    libchromatix_imx179_sunny_video_binning \
    libchromatix_imx377_common \
    libchromatix_imx377_cpp_hfr_120 \
    libchromatix_imx377_cpp_hfr_240 \
    libchromatix_imx377_cpp_hfr_60 \
    libchromatix_imx377_cpp_hfr_90 \
    libchromatix_imx377_cpp_liveshot \
    libchromatix_imx377_cpp_preview \
    libchromatix_imx377_cpp_snapshot \
    libchromatix_imx377_cpp_uhd_video \
    libchromatix_imx377_cpp_video \
    libchromatix_imx377_default_video \
    libchromatix_imx377_hfr_120 \
    libchromatix_imx377_hfr_240 \
    libchromatix_imx377_hfr_60 \
    libchromatix_imx377_hfr_90 \
    libchromatix_imx377_liveshot \
    libchromatix_imx377_postproc \
    libchromatix_imx377_preview \
    libchromatix_imx377_snapshot \
    libflash_pmic \
    libgoog_eis_armeabi-v7a \
    libgoog_rownr \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_is \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_vpe_module \
    libmmcamera2_wnr_module \
    libmmcamera_cac2_lib \
    libmmcamera_dw9761b_eeprom \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_faceproc \
    libmmcamera_imx179_liteon \
    libmmcamera_imx179_sunny \
    libmmcamera_imx377 \
    libmmcamera_isp_abcc44 \
    libmmcamera_isp_abf44 \
    libmmcamera_isp_bcc44 \
    libmmcamera_isp_be_stats44 \
    libmmcamera_isp_bf_scale_stats46 \
    libmmcamera_isp_bf_stats44 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_bpc44 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_clf46 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_demosaic44 \
    libmmcamera_isp_demux40 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_hdr46 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm44 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_sub_module \
    libmmcamera_m24c64s_eeprom \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_sony_imx179_eeprom \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_vpu_module \
    libmmipl \
    libmmjpeg \
    libmmqjpeg_codec \
    libmmqjpegdma \
    liboemcamera \
    liboemcrypto \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    librs.rnr_downscale \
    librs.rnr_process \
    libfmas \
    fingerprint.angler \
    flp.default \
    lib_fpc_tac_shared \
    libcallutils \
    libdisp-aba \
    libgeofence \
    libhwgetnv \
    libhwnv \
    libhwsarcontrol \
    libizat_core \
    liblbs_core \
    liblowi_client \
    liblowi_wifihal \
    liblqe \
    libqdp \
    libqmi_oem_api \
    libquipc_os_api \
    libril-qc-qmi-1 \
    libthermalioctl \
    ATFWD-daemon \
    InputEventFind \
    cnd \
    diag_klog \
    diag_mdlog \
    diag_test_server \
    dsm_ctrl \
    ims_rtp_daemon \
    imscmservice \
    imsdatadaemon \
    imsqmidaemon \
    irsc_util \
    loc_launcher \
    mm-qcamera-daemon \
    msm_irqbalance \
    netmgrd \
    nl_listener \
    oem_qmi_server \
    perfd \
    pm-proxy \
    pm-service \
    port-bridge \
    qmuxd \
    qseecomd \
    qti \
    radish \
    rmt_storage \
    slim_daemon \
    sound_trigger_test \
    ssr_setup \
    subsystem_ramdump \
    thermal-engine
